[package]
name = "m2proxy"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = {version = "1.1.0", features = ["full","io-util"]}
futures = { version = "0.3.0", features = ["thread-pool"]}
tokio-stream = "0.1"

